# Generated by Django 5.0.3 on 2024-04-14 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_name',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
