# Generated by Django 5.0.3 on 2024-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_alter_upload_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='alias',
            field=models.CharField(default='c', max_length=30),
            preserve_default=False,
        ),
    ]
